### ISSUE TITLE
Settings publish doesn't work

### ISSUE THREAD

**Issue by RomkaLTU** [GENL/matice#14] opened 2021-03-21 20:09 UTC
### Expected behavior

Settings published to config dir

### Current behavior

```
php artisan vendor:publish --provider=Genl\Matice\MaticeServiceProvider
Unable to locate publishable resources.
```

### Versions

- **Laravel**: 8.33.1
- **Matice**: 1.1.6

**Comment by GENL** [comment] 2021-03-21 21:04
Sorry. It works well on my end. Check if the package is installed correctly.

**Comment by RomkaLTU** [comment] 2021-03-22 06:24
Yeah, that's strange. I just looked to MaticeServiceProvider, and it looks fine. No idea why it's cant publish config. Anyway package is working, and I don't need to change default values so far.

**Comment by GENL** [comment] 2021-03-22 12:23
Ok. Later try to remove and install the package again.

I'll close the issue,

**Closed as completed by GENL** 2021-03-22 12:23 UTC

**Comment by nyneplus** [comment] 2021-03-23 07:49
I have the same problem today... The config file is there, caches are all cleared, etc... I will try to figure out the cause, or i copy it manually but if anyone has an idea i would be most thankful.

**Comment by RomkaLTU** [comment] 2021-03-23 07:51
You need to define provider with surrounded "

```
php artisan vendor:publish --provider="Genl\Matice\MaticeServiceProvider"
```

But that's opens another problem I posted here: https://github.com/GENL/matice/issues/16

**Comment by nyneplus** [comment] 2021-03-23 07:55
> 
> 
> You need to define provider with surrounded "
> 
> ```
> php artisan vendor:publish --provider="Genl\Matice\MaticeServiceProvider"
> ```
> 
> But that's opens another problem I posted here: #16

That does indeed work. May be it should be changed in the readme too. I hoop #16 is solved soon too. That looks simple enough.

**Comment by GENL** [comment] 2021-03-23 17:14
Changed in the README,
